"""
core/detector_engine.py
========================
A modular detection pipeline that processes every TraceEvent through a list of
registered BaseDetector implementations.

Design goals:
  - Adding a new detection capability = one new file + one registration line.
  - Zero modification to existing event sources (DebugThread, MemoryScannerThread).
  - Each detector is isolated: a crash in one does NOT kill the others.

Architecture:
  DebugThread / MemoryScannerThread
        |
        v
  event_queue  (queue.Queue[TraceEvent])
        |
        v
  DetectorEngine.process(event)
        |
        +---> Detector A -> [extra_events or []]
        +---> Detector B -> [extra_events or []]
        +---> Detector C -> [extra_events or []]
        |
        v
  All extra events are emitted back to the event_queue
"""

import logging
from typing import List

from bx2trace.core.models import BaseDetector, TraceEvent

_log = logging.getLogger("bx2trace.detector_engine")


class DetectorEngine:
    """
    Orchestrates all registered detectors.

    Usage::

        engine = DetectorEngine()
        engine.register(ProcessHollowingDetector())
        engine.register(ShellcodeDetector())

        # Inside the event consumer loop:
        extra = engine.process(event)
        for e in extra:
            emit(e)

    Detectors are called in registration order.
    Registration supports chaining: engine.register(A).register(B).register(C)
    """

    def __init__(self):
        self._detectors: List[BaseDetector] = []

    def register(self, detector: BaseDetector) -> "DetectorEngine":
        """
        Register a detector. Returns self to enable chaining.

        Example::

            engine.register(DetectorA()).register(DetectorB())
        """
        if not isinstance(detector, BaseDetector):
            raise TypeError(
                f"detector must be an instance of BaseDetector, got {type(detector).__name__}"
            )
        self._detectors.append(detector)
        _log.debug("Registered detector: %s", detector.name)
        return self

    def unregister(self, name: str) -> bool:
        """
        Remove a detector by name. Returns True if found and removed.
        Useful during tests or dynamic reconfiguration.
        """
        before = len(self._detectors)
        self._detectors = [d for d in self._detectors if d.name != name]
        removed = len(self._detectors) < before
        if removed:
            _log.debug("Unregistered detector: %s", name)
        return removed

    def process(self, event: TraceEvent) -> List[TraceEvent]:
        """
        Pass event through all registered detectors.

        Each detector that handles the event returns zero or more derived
        TraceEvent objects. All results are collected and returned.

        A detector that raises an exception is logged and skipped —
        it does NOT interrupt the processing pipeline.

        Returns:
            List of extra events generated by detectors (may be empty).
        """
        extra_events: List[TraceEvent] = []

        for detector in self._detectors:
            try:
                if detector.handles(event):
                    results = detector.process(event)
                    if results:
                        extra_events.extend(results)
            except Exception as exc:  # noqa: BLE001
                # Isolate each detector — a crash in one does NOT kill the pipeline.
                _log.warning(
                    "Detector '%s' raised an exception on event %s/%s: %s",
                    detector.name,
                    event.category,
                    event.action,
                    exc,
                    exc_info=False,  # avoid log flood on repetitive errors
                )

        return extra_events

    @property
    def detector_names(self) -> List[str]:
        """Returns the names of all registered detectors (for diagnostics/logging)."""
        return [d.name for d in self._detectors]

    def load_defaults(self) -> "DetectorEngine":
        """
        Registers all built-in detectors in a single call.

        Can be combined with custom detectors before or after::

            # Only built-ins:
            engine.load_defaults()

            # Built-ins + your own detector on top:
            engine.load_defaults().register(MyDetector())

            # Your own detector only (skip built-ins entirely):
            engine.register(MyDetector())

        Returns:
            self — to enable method chaining.
        """
        # Lazy imports: keeps the top-level import cost zero for callers
        # that only use a subset of detectors.
        from bx2trace.detectors.process_hollow_detector import ProcessHollowingDetector
        from bx2trace.detectors.registry_persistence_detector import RegistryPersistenceDetector
        from bx2trace.detectors.c2_beacon_detector import C2BeaconDetector

        self.register(ProcessHollowingDetector())
        self.register(RegistryPersistenceDetector())
        self.register(C2BeaconDetector())
        _log.debug("load_defaults: registered %d built-in detectors.", 3)
        return self

    def __len__(self) -> int:
        return len(self._detectors)

    def __repr__(self) -> str:
        return f"DetectorEngine(detectors={self.detector_names})"

